In [11]:

import os as os
import itertools as itt

import numpy as np
import pandas as pd

path = '/TL/deep/fhgfs/projects/pebert/thesis/projects/statediff/temp/test_deseq/deseq_out'
fname = 'deseq2_Ma_vs_Mo.tsv'

use_genes = pd.read_csv('/TL/deep/fhgfs/projects/pebert/thesis/projects/statediff/references/gencode_v21_pcg_bglist.bed',
                        header=0, sep='\t')

df = pd.read_csv(os.path.join(path, fname), sep='\t', header=None,
                 names=['name', 'baseMean', 'log2FoldChange', 'lfcSE', 'stat', 'pvalue', 'padj'],
                 skiprows=1)
df['name'] = df['name'].str.extract('(?P<ENSID>\w+)', expand=False)
df = df.loc[df['name'].isin(use_genes['name']), :].copy()
df.fillna(-1, inplace=True)
regular = df.loc[df['padj'] != -1, :]
print(regular.shape)
#deg1 = regular.loc[regular['padj'] < 0.05, :]
select_de = np.logical_and(regular['padj'] < 0.01, regular['log2FoldChange'].abs() > 2)
deg1 = regular.loc[select_de, :]
print(deg1.shape)

sub_bed = use_genes.loc[use_genes['name'].isin(deg1['name']), :]
out_bed = os.path.join('/TL/deep/fhgfs/projects/pebert/thesis/projects/statediff/temp/deg_Ma_vs_Mo.bed')
sub_bed.to_csv(out_bed, sep='\t', header=True, index=False)

print('Original stats')

src_path = '/TL/deep/fhgfs/projects/pebert/thesis/projects/statediff/deseq/deep'
src_file = 'deseq2_Ma_vs_Mo.tsv'

df2 = pd.read_csv(os.path.join(src_path, src_file), sep='\t', header=None,
                  names=['name', 'baseMean', 'log2FoldChange', 'lfcSE', 'stat', 'pvalue', 'padj'],
                  skiprows=1)
df2['name'] = df2['name'].str.extract('(?P<ENSID>\w+)', expand=False)
df2 = df2.loc[df2['name'].isin(use_genes['name']), :].copy()
df2.fillna(-1, inplace=True)
reg2 = df2.loc[df2['padj'] != -1, :]
print(reg2.shape)
#deg2 = reg2.loc[reg2['padj'] < 0.05, :]
select_de = np.logical_and(reg2['padj'] < 0.01, reg2['log2FoldChange'].abs() > 2)
deg2 = reg2.loc[select_de, :]
print(deg2.shape)

intersect = set(deg2['name']).intersection(set(deg1['name']))
union = set(deg2['name']).union(set(deg1['name']))

print(len(intersect) / len(union))


(16311, 7)
(2211, 7)
Original stats
(16334, 7)
(2409, 7)
0.7983651226158038
(101552, 4)
[ 3.  5. 12.]
[7.87906553e+08 2.46682722e+10 1.19389361e+11]
(2166, 4)
(121880, 4)
[ 3.  6. 15.]
[3.44460569e+09 3.79883899e+10 1.60709089e+11]
(1874, 4)
[('A', 'A'), ('A', 'B'), ('A', 'C'), ('B', 'B'), ('B', 'C'), ('C', 'C')]
